[[MibS]]
arch = "aarch64"
git-tree-sha1 = "1ec3a50f32cfb25d1adb7dc950d0d7c6e39147a8"
os = "macos"

    [[MibS.download]]
    sha256 = "46f56f4c1a03917b01ddc9f4bf2024b838f20c3837a744863230d1c90b1021b3"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.aarch64-apple-darwin.tar.gz"
[[MibS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d4fbf69d9349ceeb398ddf9ab2b0ce0bd527a75"
libc = "glibc"
os = "linux"

    [[MibS.download]]
    sha256 = "841e2b4e26aea2983b4a0d6438aa6c3b7f075ead6e6b5f62798565a2bcd4503b"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.aarch64-linux-gnu-cxx03.tar.gz"
[[MibS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "353eefc8099b34e433898d9618523b20cf191249"
libc = "glibc"
os = "linux"

    [[MibS.download]]
    sha256 = "c2477b8fee75515bc93d8d7f1d60c9ff86d37e6004eee57f1a2816156be38361"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.aarch64-linux-gnu-cxx11.tar.gz"
[[MibS]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d5386bdabe4e701b7c58f063a9690346b1f5ae4"
libc = "musl"
os = "linux"

    [[MibS.download]]
    sha256 = "5837705767d7d734d9886584800a6896c0779aa2e8ab490e79d03859129094b7"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.aarch64-linux-musl-cxx03.tar.gz"
[[MibS]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5280c3da3a599927604c4f02f03a105306de6f39"
libc = "musl"
os = "linux"

    [[MibS.download]]
    sha256 = "bf96e95d10e5281ecc80831cdcf3380dd2cf27126c2a6c19cba81f867d68b74f"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.aarch64-linux-musl-cxx11.tar.gz"
[[MibS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9326e7c80a4e97eaabb81e963cca6deeb08d95d3"
libc = "glibc"
os = "linux"

    [[MibS.download]]
    sha256 = "3f1f0c5cb6f10488f9f596488213028a6cdecc721901dc485dc02046092f9b3c"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MibS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d34084dfc3595fed9539bccf185161462f5d4c8"
libc = "glibc"
os = "linux"

    [[MibS.download]]
    sha256 = "d724d954f05d147b2f3a00ab5fd7b724ce9d79a14e89017c4fbe7bbbc41ea891"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MibS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3799d3fbe56b11318507d503f2ea2277d48f3875"
libc = "musl"
os = "linux"

    [[MibS.download]]
    sha256 = "56660f25dcdb41a5fd36cc0d62eca6d88694026a8c850b9c667197e01f517df8"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MibS]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58f2312da676f99f0671aeaa1dbe3f36b311acdd"
libc = "musl"
os = "linux"

    [[MibS.download]]
    sha256 = "856d90f8ab55fb31ae02972e9e008338d65fc90985d62cf5446c4a839f03d4f9"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MibS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "78f9ecd7b1c471de58069b9f9efe82f12a9c5105"
libc = "glibc"
os = "linux"

    [[MibS.download]]
    sha256 = "382e189631a046fbf18caeae42f3c0ca4364f40f598954adcd61829fba900546"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MibS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50c07319c3d517da69c601cacfbd9f9ddd8a1ec3"
libc = "glibc"
os = "linux"

    [[MibS.download]]
    sha256 = "4f1598e1ca1432d407ca5e4c9cfde4cf40874b003fa05536092168908c8e8344"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MibS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e58fd7edcafebd35e6bbb985efc8138575f7e1f2"
libc = "musl"
os = "linux"

    [[MibS.download]]
    sha256 = "b478b1534cef89451dcf37f436ac794017628b1b66683f2e33a99db5b00e8768"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MibS]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2eaeb394e4ace97c5bde347a551d5751252d09f0"
libc = "musl"
os = "linux"

    [[MibS.download]]
    sha256 = "bd973b60104f6cdc0675be911b88a68806c1b3668cb211c9aa50e9dcd9bd5b67"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MibS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5692d1bc704fdb6aef0c2c149c687ab38d7982e"
libc = "glibc"
os = "linux"

    [[MibS.download]]
    sha256 = "4f10b353c25b477cc8bcb9c62225ccb989a5f531babf3f6deca87704d47c2b96"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.i686-linux-gnu-cxx03.tar.gz"
[[MibS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aed78f3c6f7d0b4e29b16eaa0b62f9331393ae8f"
libc = "glibc"
os = "linux"

    [[MibS.download]]
    sha256 = "250d694cc501c2d5a1355fa1d2ecbcd203bdc931de54b9c02b00140448807cc5"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.i686-linux-gnu-cxx11.tar.gz"
[[MibS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae5571725382e7a420619da208a76fd119b05f35"
libc = "musl"
os = "linux"

    [[MibS.download]]
    sha256 = "14b05042c2f00ed12b886a784e6d38ac2ad56f20f535a3b391d452ad7059ca74"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.i686-linux-musl-cxx03.tar.gz"
[[MibS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "725c5ba7cf5f55ad85d083f09a31f355da3e3388"
libc = "musl"
os = "linux"

    [[MibS.download]]
    sha256 = "c7e3f790b0ab06f6fcf43b575c21837dd3a15c0237a351f6277acde317e371c5"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.i686-linux-musl-cxx11.tar.gz"
[[MibS]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9effdec551e4407f4c7d6f377a1f21f31d2df30"
os = "windows"

    [[MibS.download]]
    sha256 = "8b7e6944003370dc7f6077a52ead8f6f093657309ef8e08e85c6dc93ed4b06dc"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.i686-w64-mingw32-cxx03.tar.gz"
[[MibS]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9454146235bfc46fee52bf56a6f37984d25f4540"
os = "windows"

    [[MibS.download]]
    sha256 = "09e1ef6379246b892645fdc8eaf8fb30d7b4a596076365ac33b4dd78bd021bfd"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.i686-w64-mingw32-cxx11.tar.gz"
[[MibS]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08075972765d18f5eeced08d758964decacb350d"
libc = "glibc"
os = "linux"

    [[MibS.download]]
    sha256 = "c04ff5d252e134e235bd74094ee426bb87f4333e2cac7420085f521f38ad8191"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MibS]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5cc4f8f63cd64aafc00add5175e6caef79068073"
libc = "glibc"
os = "linux"

    [[MibS.download]]
    sha256 = "ae871b0a3c9ca9139252ac3c4a2451b73ff472d6b97a9367ed666debb73706b7"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MibS]]
arch = "x86_64"
git-tree-sha1 = "474d3f9c24cfd54760e8114d7e56c9c65dc3c950"
os = "macos"

    [[MibS.download]]
    sha256 = "ef35fadc2dc5e48ef97d8a48a2d5fc44c3fe705390374f7d4096c90a3e35f237"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.x86_64-apple-darwin.tar.gz"
[[MibS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdde60046cef7fc0a63b0c5a565279119ec7f538"
libc = "glibc"
os = "linux"

    [[MibS.download]]
    sha256 = "635b296c7bcff81b69abc5c9507b1b327d4eb0fdd6013dda7b69f2c6ae12eca9"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.x86_64-linux-gnu-cxx03.tar.gz"
[[MibS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22e8e468a03a1735ba40db859bb3951da5edfbbb"
libc = "glibc"
os = "linux"

    [[MibS.download]]
    sha256 = "53394e9936f05c4c910fc29ab461b5c0f79a9575e0d41a73f16a85f3921516e6"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.x86_64-linux-gnu-cxx11.tar.gz"
[[MibS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d427798cd360b131db07cae4757fa6a6721d8e1"
libc = "musl"
os = "linux"

    [[MibS.download]]
    sha256 = "a0a7b531da01c7b9afcc68a3deea098357e43f3389827ef0a77ff173545607d6"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.x86_64-linux-musl-cxx03.tar.gz"
[[MibS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fae520757f52b6d62f2dfbaef698c7555d1e071"
libc = "musl"
os = "linux"

    [[MibS.download]]
    sha256 = "aef99ff224797a5219bc7d4c47d291abc4b3c5e6814e0b756399cd5e84a77fb7"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.x86_64-linux-musl-cxx11.tar.gz"
[[MibS]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "725c64a03957fbc4f3c4789776be8a89d9352acb"
os = "windows"

    [[MibS.download]]
    sha256 = "137582312459e53cbe4de14813676dcb6d66ea94af1db628a32f491bd95d0cd1"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.x86_64-w64-mingw32-cxx03.tar.gz"
[[MibS]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9eee57de059d200bfa94d992bb0a8ed83e3943b0"
os = "windows"

    [[MibS.download]]
    sha256 = "cc22f834b06946020bfc3693fb16856b14ea3f9e8479719a396c01af47e7d351"
    url = "https://github.com/JuliaBinaryWrappers/MibS_jll.jl/releases/download/MibS-v100.100.301+0/MibS.v100.100.301.x86_64-w64-mingw32-cxx11.tar.gz"
